#!/usr/bin/env python2.5
#-*- coding: utf-8 -*-
# mStore is a store management system for small shops. Delivered to Nokia tablets.
"""
    This file is part of mStore.

    mStore is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    mStore is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with mStore.  If not, see <http://www.gnu.org/licenses/>.
"""
import sys,os

os.chdir('/usr/share/mstore')

sys.path.append('/usr/share/mstore')

if __name__ == '__main__':
  from  main import *
  app.run()
